/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;

public class App {

    public final static int TOTAL_CARROS = 3;
    public final static int TOTAL_PECAS = 3;

    private ArrayList<Jogador> jogadores;

    public App () {
        jogadores = new ArrayList<>();
    }

    public void criarJogador (String nome) {
        Motor m = new Motor(120, 4);
        Carro c = new Carro("ferrari", m);
        Jogador j = new Jogador(nome, c);
        this.jogadores.add(j);
    }

    public void comprarCarro (Jogador j, Carro c) {
        if (j.comprarCarro(c)) {
            System.out.println("Carro comprado com sucesso");
        } else {
            System.out.println("Garagem cheia");
        }

    }

    public void comprarMotor (Jogador j) {
        if (j.comprarMotor(new Motor(200, 6))) {
            System.out.println("Motor comprado com sucesso");
        } else  {
            System.out.println("Estante cheia");
        }
    }

    public void venderCarro (Jogador j, int posicao) {

        j.venderCarro(posicao);

    }

    public static void main (String[] args) {

        App app = new App();

        app.criarJogador("Juca");

        app.comprarMotor(app.jogadores.get(0));

        app.criarJogador("Computador");

        app.comprarCarro(app.jogadores.get(0), new Carro("fusca", new Motor(300, 4)));
        app.comprarCarro(app.jogadores.get(0), new Carro("gol", new Motor(300, 4)));
        app.comprarCarro(app.jogadores.get(0), new Carro("celta", new Motor(300, 4)));

        app.comprarCarro(app.jogadores.get(1), new Carro("uno", new Motor(300, 4)));
        app.comprarCarro(app.jogadores.get(1), new Carro("hb20", new Motor(300, 4)));
        app.comprarCarro(app.jogadores.get(1), new Carro("cruze", new Motor(300, 4)));



        System.out.println("Antes de vender");

        app.venderCarro(app.jogadores.get(0), 0);

        app.jogadores.remove(0);

        System.out.println("Fim");

    }
    

}
