/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;

public class App {

    public final static int TOTAL_CARROS = 3;
    public final static int TOTAL_PECAS = 3;

    private ArrayList<Jogador> jogadores;

    public App () {
        jogadores = new ArrayList<>();
    }

    public void criarJogador (String nome) {
        Motor m = new Motor(120, 4);
        Carro c = new Carro("ferrari", m);
        Jogador j = new Jogador(nome, c);
        this.jogadores.add(j);
    }

    public void comprarCarro (Jogador j) {
        if (j.comprarCarro(new Carro("fusca", new Motor(400, 4)))) {
            System.out.println("Carro comprado com sucesso");
        } else {
            System.out.println("Garagem cheia");
        }

    }

    public void comprarMotor (Jogador j) {
        if (j.comprarMotor(new Motor(200, 6))) {
            System.out.println("Motor comprado com sucesso");
        } else  {
            System.out.println("Estante cheia");
        }
    }

    public static void main (String[] args) {

        App app = new App();

        app.criarJogador("Juca");
        app.criarJogador("Computador");

        app.comprarCarro(app.jogadores.get(0));

    }
    

}
