/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Data a = new Data(24, 8, 2023);
        Data b = new Data(25, 8, 2023);

        int diferencaDias = a.diferencaEmDias(b);

        Scanner teclado = new Scanner(System.in);

        System.out.print("Entre com o dia: ");
        int dia = teclado.nextInt();
        System.out.print("Entre com o mês: ");
        int mes = teclado.nextInt();
        System.out.print("Entre com o ano: ");
        int ano = teclado.nextInt();

        Data d = new Data(dia, mes, ano);

        System.out.println(d);

        do {
            System.out.print("Entre com o mês: ");
            mes = teclado.nextInt();
        } while (!d.setMes(mes));

        System.out.println(d);

    }

}
