/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import produtos.Celular;
import produtos.SemFio;
import produtos.Telefone;

public class App {

    public static void main(String[] args) {

        Telefone pleno = new Telefone(1,"123","pleno",0.3,new Dimensao(1,2,3));
        SemFio sf = new SemFio(2,"456", "sem fio", 0.5, new Dimensao(2,2,2), 1.8, 14, 40);
        Celular c = new Celular(2,"456", "sem fio", 0.5, new Dimensao(2,2,2), 1.8, 14, 40, "Android");

        pleno.setModelo("novo");
        sf.setCanais(2);
        c.setSistemaOperacional("ios");

        Telefone outro = c;
        SemFio nova = (SemFio) outro;


    }
}
