/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    public static String formataCep(String numero) throws ParseException {

        MaskFormatter mascara = new MaskFormatter("#####-###");

        return "";

    }

    public static String formataTelefone(String numero) {

        try {
            MaskFormatter mascara = new MaskFormatter("(##) #####-####");
        } catch (ParseException e) {
            System.err.println("valor errado");
    }

        return "";
    }

    public static void main(String[] args) throws ParseException {

        String formatado = formataTelefone("48991525985");

        String cepFormatado = formataCep("88134700");

        System.out.println(cepFormatado);

        System.out.println("Fim do programa!");

        //    Scanner ler = new Scanner(System.in);
//        int a, b;
//
//        try {
//            a = ler.nextInt();
//            b = ler.nextInt();
//
//            int res = a / b;
//
//            System.out.println(a + " dividido por " + b + " = " + res);
//        } catch (InputMismatchException e) {
//            System.err.println("Entrou com valor diferente de int");
//        } catch (ArithmeticException e) {
//            System.err.println("Divisão por zero");
//        } catch (Exception e) {
//            System.err.println("Comportamento inesperado");
//        }
    }
}
