/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.Collections;

public class App {

    public static void main(String[] args) {

        ArrayList<Carta> baralho = new ArrayList<>();

        for (Valor v: Valor.values()) {
            if (v.valor != -1) {
                for (Naipe n: Naipe.values()) {
                    baralho.add(new Carta(v,n));
                }
            }
        }

        Collections.shuffle(baralho);

        for (Carta c: baralho) {
            System.out.println(c);
        }

        Carta c1 = baralho.get(0);
        Carta c2 = baralho.get(1);

        if (c1.getValor().valor > c2.getValor().valor) {
            System.out.println("c1 venceu!");
        } else if (c2.getValor().valor > c1.getValor().valor) {
            System.out.println("c2 venceu!");
        } else {
            System.out.println("empate");
        }

    }
}
