/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class App {

    public static void main (String[] args ) {

        Aluno joao = new Aluno(123, "João");
        Aluno maria = new Aluno(456, "Maria");

//        String sje = "São José";
//        String fln = "Florianópolis";
//        ArrayList<Aluno> alunos = new ArrayList<>();
//        ArrayList<String> cidades = new ArrayList<>();

//        alunos.add(joao);
//        alunos.add(maria);

        Map<Integer, Aluno> alunos = new HashMap<>();

        alunos.put(maria.getMatricula(), joao);
        alunos.put(joao.getMatricula(), maria);

//        cidades.add(sje);
//        cidades.add(fln);
//
//        String outra = "Florianópolis";
//
//        if (cidades.contains("Florianópolis")) {
//            System.out.println("Tem Floripa");
//        } else {
//            System.out.println("Não tem Floripa");
//        }
//
//        if (alunos.contains(joao)) {
//            System.out.println("Tem João");
//        } else {
//            System.out.println("Não tem João");
//        }
//
//        alunos.forEach(a->{
//            if (a.getMatricula() == 123) {
//                System.out.println("Tem João");
//            }
//        });
//
//        alunos.removeIf(a->a.getMatricula() == 123);

    }

    /*nome   : String            atributos simples
    codigo   : String                      ||
    sigla    : String
    creditos : Integer
    semanas  : Integer
    ementa   : String
    objetivos: ArrayList<String> atributos nao simples
    conteudo : ArrayList<String>           ||


    getCargaHoraria();
     */

}
