/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import raytracer.ABunchOfSpheres;

import java.time.Duration;
import java.time.Instant;

public class App {

    public static void main(String[] args) {

        Thread movie = new Thread(new Filme());
        Instant inicio = Instant.now();
        for (int i = 0; i < 30; i++) {
            movie.start();
        }
        Instant fim = Instant.now();
        Duration d = Duration.between(inicio, fim);
        System.out.println("Tempo decorrido em milissegundos " + d.toMillis());

//        Contador c = new Contador();
//
//        Thread comHeranca = new FluxoComHeranca();
//        comHeranca.start();
//
//        Thread comInterface1 = new Thread(new FluxoComInterface(c, 1));
//        Thread comInterface2 = new Thread(new FluxoComInterface(c, 2));
//
//        System.err.println("Inicio do programa");
//
//        comInterface1.start();
//        comInterface2.start();
//
//        System.err.println("Fim do programa");

//        Contador c = new Contador();
//        Fluxo f1 = new Fluxo(c, 1);
//        Fluxo f2 = new Fluxo(c, 2);
//        System.out.println("Inicio");
//        f1.disparar();
//        f2.disparar();
//        System.out.println("Fim do programa");

    }


}
