/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    private Area area;
    private Robo robo;

    public static void main(String[] args) {

    }
}
