/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;
import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static final int MAX_X = 600;
    public static final int MIN_X = 0;
    public static final int MAX_Y = 600;
    public static final int MIN_Y = 0;

    private Area area;
    private Robo robo;
    private Draw desenho;

    public App () {
        this.desenho = new Draw();
        this.desenho.setXscale(MIN_X,MAX_X);
        this.desenho.setYscale(MIN_Y,MAX_Y);
        this.desenho.enableDoubleBuffering();
        this.desenho.setDefaultCloseOperation(3);
    }

    public void desenharQuadrado (int x, int y, int dimensao) {
        desenho.setPenColor(Color.RED);
        desenho.filledSquare(x, y, dimensao);
    }

    public void desenharCirculo (int x, int y, int raio) {
        desenho.setPenColor(Color.BLUE);
        desenho.filledCircle(x, y, raio);
    }

    public static void main(String[] args) {

        App app = new App();

        Area mapa = new Area(MAX_X,MAX_Y,3);

        ArrayList<Elemento> elementos = new ArrayList<>();

        elementos.add(new Robo(mapa,300,0,30,30,3));
//        int x = 350;
//        int y = 350;
//        int raio = 10;
//        int vx = 1;
//        int vy = 2;

        while (true) {
            // Atualiza as coordenadas dos elementos
            for (var e: elementos) {
                System.out.println("w, a, s, d = direções;");
                System.out.println("x = cavar");
                if (e instanceof Robo) {
                    Robo r = (Robo) e;
                        String direcao = new Scanner(System.in).nextLine();
                        if (direcao.equals("w")) r.movimentar(Robo.CIMA);
                        if (direcao.equals("s")) r.movimentar(Robo.BAIXO);
                        if (direcao.equals("a")) r.movimentar(Robo.ESQUERDA);
                        if (direcao.equals("d")) r.movimentar(Robo.DIREITA);
                        if (direcao.equals("x")) r.cavar();
                }
            }

            // Desenha os elementos com novas coordenadas
            elementos.forEach(e->e.desenhar(app.desenho));
            mapa.desenhar(app.desenho);

            app.desenho.pause(10);
            app.desenho.show();
            app.desenho.clear(Color.WHITE);

//            app.desenharQuadrado(300, 300, 20);
//            app.desenharCirculo(x, y,raio);
//
//            x+= vx;
//            y+= vy;
//
//            if (x+raio > 600 || x-raio < 0) {
//                vx *= -1;
//            }
//
//            if (y+raio > 600 || y-raio < 0) {
//                vy *= -1;
//            }
//
//            Rectangle r = new Rectangle(280, 280, 40, 40);
//            Rectangle b = new Rectangle(x-raio, y-raio, 2*raio, 2*raio);
//
//            if (r.intersects(b)) {
//                if (x > 320 || x < 280) {
//                    vx *= -1;
//                }
//                if (y > 320 || y < 280)  {
//                    vy *= -1;
//                }
//            }
        }

    }
}
